#!/usr/bin/env python

import os
import sys
import time
import socket

# disable output buffering
sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)

SYSFS_BCACHE_PATH = '/sys/fs/bcache/'

hostname = os.environ['COLLECTD_HOSTNAME'] if 'COLLECTD_HOSTNAME' in os.environ else socket.getfqdn()
interval = float(os.environ['COLLECTD_INTERVAL']) if 'COLLECTD_INTERVAL' in os.environ else 1


def file_to_lines(fname):
    try:
        with open(fname, "r") as fd:
            return fd.readlines()
    except:
        return []


def file_to_line(fname):
    ret = file_to_lines(fname)
    if ret:
        return ret[0].strip()
    return ''


def interpret_bytes(x):
    '''Interpret a pretty-printed disk size.'''
    factors = {
        'k': 1 << 10,
        'M': 1 << 20,
        'G': 1 << 30,
        'T': 1 << 40,
        'P': 1 << 50,
        'E': 1 << 60,
        'Z': 1 << 70,
        'Y': 1 << 80,
    }

    factor = 1
    if x[-1] in factors:
        factor = factors[x[-1]]
        x = x[:-1]
    return int(float(x) * factor)


def bcache_uuids():
    uuids = []

    if not os.path.isdir(SYSFS_BCACHE_PATH):
        print('bcache is not loaded.')
        return uuids

    for cache in os.listdir(SYSFS_BCACHE_PATH):
        if not os.path.isdir('%s%s' % (SYSFS_BCACHE_PATH, cache)):
            continue
        uuids.append(cache)

    return uuids


def get_dirty_data(uuid):
    dirty_data = 0
    for obj in os.listdir(os.path.join(SYSFS_BCACHE_PATH, uuid)):
        if obj.startswith('bdev'):
            val = interpret_bytes(file_to_line('%s/%s/%s/dirty_data' %
                                               (SYSFS_BCACHE_PATH, uuid, obj)))
            dirty_data = dirty_data + int(val)
    return dirty_data


def get_cache_ratio(uuid, time):
    for obj in os.listdir(os.path.join(SYSFS_BCACHE_PATH, uuid)):
        if obj.startswith('bdev'):
            hits = float(file_to_line('%s/%s/%s/stats_%s/cache_hits' %
                                    (SYSFS_BCACHE_PATH, uuid, obj, time)))
            misses = float(file_to_line('%s/%s/%s/stats_%s/cache_misses' %
                                      (SYSFS_BCACHE_PATH, uuid, obj, time)))
            if (hits + misses) == 0:
                return 100
            return hits / (hits + misses) * 100
    return 0


def get_cache_result(uuid, stat):
    value = 0
    for obj in os.listdir(os.path.join(SYSFS_BCACHE_PATH, uuid)):
        if obj.startswith('bdev'):
            value = int(file_to_line('%s/%s/%s/stats_five_minute/cache_%s' %
                                    (SYSFS_BCACHE_PATH, uuid, obj, stat)))
    return value


def get_bypassed(uuid):
    value = 0
    for obj in os.listdir(os.path.join(SYSFS_BCACHE_PATH, uuid)):
        if obj.startswith('bdev'):
            value = interpret_bytes(file_to_line('%s/%s/%s/stats_five_minute/bypassed' %
                                               (SYSFS_BCACHE_PATH, uuid, obj)))
    return value


def map_uuid_to_bcache(uuid):
    for obj in os.listdir(os.path.join(SYSFS_BCACHE_PATH, uuid)):
        if obj.startswith('bdev'):
           return os.path.basename(os.readlink(os.path.join(SYSFS_BCACHE_PATH, uuid, obj, 'dev')))


def main():
    while True:
        uuids = bcache_uuids()
        for uuid in uuids:
            dirty_data = get_dirty_data(uuid)
            device = map_uuid_to_bcache(uuid)
            print('PUTVAL "%s/bcache-%s/df_complex-dirty_data" interval=%s N:%s' %
                  (hostname, device, interval, dirty_data))
            for t in ['five_minute', 'hour', 'day', 'total']:
                cache_ratio = get_cache_ratio(uuid, t)
                print('PUTVAL "%s/bcache-%s/cache_ratio-%s" interval=%s N:%s' %
                      (hostname, device, t, interval, cache_ratio))
            for c in ['bypass_hits', 'bypass_misses', 'hits', 'miss_collisions', 'misses', 'readaheads']:
                cache_result = get_cache_result(uuid, c)
                print('PUTVAL "%s/bcache-%s/requests-%s" interval=%s N:%s' %
                      (hostname, device, c, interval, cache_result))
            bypassed = get_bypassed(uuid)
            print('PUTVAL "%s/bcache-%s/bytes-bypassed" interval=%s N:%s' %
                  (hostname, device, interval, bypassed))
        time.sleep(interval)


if __name__ == '__main__':
    main()
