#!/bin/sh

set -e
set -u

PROG=`basename $0`
CONF=/etc/dhcp/dhcpd.conf
TIMESTAMP=/var/local/`basename $CONF`.timestamp
COPY="rsync -t"

# If $CONF does not exist, exit
if [ ! -r $CONF ]; then
	exit 0
fi

# If timestamp does not exist, create it
if [ ! -r $TIMESTAMP ]; then
	$COPY $CONF $TIMESTAMP
fi

# If config file is newer than timestamp, restart dhcpd and copy the config file to the timestamp file
if [ $CONF -nt $TIMESTAMP ]; then
	$COPY $CONF $TIMESTAMP
	if [ `ps -e|awk '$NF == "dhcpd"'|wc -l` -ne 0 ]; then
		echo "$CONF changed: restarting DHCP server"
		/etc/init.d/isc-dhcp-server restart 2>&1 | grep -v \
			-e 'Shutting down DHCP server ..done' \
			-e 'Starting DHCP server \[chroot\]..done' \
			-e 'Stopping ISC DHCP server: dhcpd' \
			-e 'Starting ISC DHCP server: dhcpd' \
				|| true
	fi
fi 2>&1 | logger -t $PROG -p user.info

