#!/bin/sh
# Check whether a reboot is needed

# verbose mode if --verbose is supplied, or if we're running from a terminal
if [ -t 0 -o "$#" -gt 1  -a  "$1" = "--verbose" ]; then
	VERBOSE="1"
else
	VERBOSE=""
fi
	
set -e
set -u

if [ -f /etc/debian_version ]; then
	# Debian-based distribution
	ret=0
	REBOOT_FILE=/var/run/reboot-required
	if [ -e $REBOOT_FILE ]; then
		cat $REBOOT_FILE
		ret=1
	fi
	REBOOT_FILE=$REBOOT_FILE.pkgs
	if [ -e $REBOOT_FILE ]; then
		echo "Reboot required due to the following package updates:"
		cat $REBOOT_FILE
		ret=2
	fi
	exit $ret
else
	# Assume RPM-based distribution
	INSTALLED="`rpm -q kernel kernel-PAE|grep -v is.not.installed|tail -1|sed -e 's/^kernel-//' -e 's/.i686$//' -e 's/.x86_64$//' -e 's/^PAE-\(.*\)$/\1PAE/'`"
	RUNNING=`uname -r|sed -e 's/.x86_64$//'`
	if [ $INSTALLED != $RUNNING -a $INSTALLED != ${RUNNING}PAE ]; then
		echo "Reboot IS required - kernel running is $RUNNING, but $INSTALLED is installed"
		exit 1
	else
		if [ -n "$VERBOSE" ]; then
			echo "Reboot not required - latest installed kernel ($RUNNING) is running"
		fi
		exit 0
	fi
fi
