#!/bin/sh
# Check whether a reboot is needed on CentOS and similar.

if [ "$#" -gt 1  -a  "$1" = "--verbose" ]; then
	VERBOSE="1"
else
	VERBOSE=""
fi
	
set -e
set -u

INSTALLED=`rpm -q kernel|tail -1|sed -e 's/^kernel-//'`
RUNNING=`uname -r`

if [ $INSTALLED != $RUNNING ]; then
	echo "Reboot needed - kernel running is $RUNNING, but $INSTALLED is installed"
	exit 1
else
	if [ -t 0  -o -n "$VERBOSE" ]; then
		echo "Reboot not required - latest installed kernel ($RUNNING) is running"
	fi
	exit 0
fi
