#! /bin/sh
#
# This script should be called by upssched via the CMDSCRIPT directive.
# ...
# The first argument passed to your CMDSCRIPT is the name of the timer
# from your AT lines.
# 
# In the configuration described here, this script is only called when
# the onbattwarn timer expires (i.e. if mains power has been gone for
# two minutes).
# 
 
case $1 in
        upsgone)
                logger -t upssched-cmd "The UPS has been gone for a while"
                ;;
        onbattwarn)
                logger -t upssched-cmd "Shutting down using: upsmon -c fsd"
                upsmon -c fsd
                ;;
        *)
                logger -t upssched-cmd "Unrecognized command: $1"
                ;;
esac
