# puppet class to manage observium

class observium {
	include observium::packages
	#include observium::pear
	#include observium::cron
}

class observium::packages {
	include apache
	include php5
	include snmp

	$common_pkgs = [

		"fping",
		"graphviz",
		"nmap",
		"php-pear",
		"rrdtool",
		"subversion",

	]
	$deb_pkgs = [

		"imagemagick",
		"ipcalc",
		"ipmitool",
		"mtr-tiny",
		"mysql-client",
		"php5-cli",
		"php5-gd",
		"php5-mysql",
		"php5-snmp",
		"php5-xcache",
		"sipcalc",
		"snmp",
		"snmp-mibs-downloader",
		"whois",

	]
	$centos_pkgs = [

		"ImageMagick",
		"jwhois",
		"mysql",
		"net-snmp-utils",
		"OpenIPMI-tools",
		"php-gd",
		"php-mysql",
		"php-pecl-apc",
		"php-snmp",

	]

	$ospkgs = $operatingsystem ? {
		Debian	=> $deb_pkgs,
		Ubuntu	=> $deb_pkgs,
		CentOS	=> $centos_pkgs,
	}
	package { $common_pkgs:
		ensure	=> installed,
	}
	package { $ospkgs:
		ensure	=> installed,
	}
}

class observium::pear {
	# TODO:
	# pear config-set http_proxy http://host:port/
	# pear install Net_IPv4
	# pear install Net_IPv6
}

class observium::cron {
	# TODO:
	# add pollem script
	# install files
}

class observium::mysql::dump {
	ulb { "observium-mysql-dump":
		source_class	=> "observium",
	}
	cron_job { "observium-mysql-dump":
		interval	=> "daily",
		script		=> "#!/bin/sh
# Generated by puppet - do not edit here
/usr/local/bin/observium-mysql-dump
",
	}
}

