#!/bin/sh

# Back up LibreNMS MySQL database - assumes MySQL is running on the same host as LibreNMS

set -e
set -u

BASE=${1:-'/opt/librenms'}
MY_CNF=${2:-"$BASE/.my.cnf"}
DUMPFILE=${3:-"$BASE/librenms.mysql.dump"}

# This is probably insecure.  If you put shell code exploits
# in your LibreNMS config.php, you're on your own.
eval `awk -F\" '
	/^[:space:]*#/ {next}
	/db_host/ {print "HOST=\"" $2 "\""}
	/db_name/ {print "NAME=\"" $2 "\""}
	/db_pass/ {print "PASS=\"" $2 "\""}
	/db_user/ {print "USER=\"" $2 "\""}
' $BASE/config.php`
echo "[client]
user=$USER
password=$PASS" > $MY_CNF

mysqldump --defaults-extra-file=$MY_CNF -h $HOST $NAME > $DUMPFILE

