
def include_header( title )
	servername = "your_server_name_here"
	header = <<HEADER
##############################################################################
# #{title}
##############################################################################
# NOTE: This file is automatically generated by puppet on #{servername}
# Changes to this file will be overwritten periodically!
##############################################################################
HEADER
	return header

end

