#!/bin/bash
#
# Author:	Paul Gear
# Created:	2010-03-16
# Modified:	2010-03-18
# Description:
#
# Report on backup statistics - call from within other backup scripts.  Output
# is in RRDtool format, consisting of the following fields:
# - time (in Unix time - number of seconds since 1 Jan 1970)
# - files modified in last day
# - files modified in last week
# - files modified in last month
# - total number of files
# - total space (in bytes) used by files
# - MB of space total on filesystem
# - MB of space used on filesystem
# - MB of space available on filesystem
# - % of space used on filesystem
#
# If --no-df is specified on the command line, the last 4 figures are skipped.
#
# If --fortnight is specified on the command line, the week interval is
# modified to 2 weeks.  Internally, all intervals are dynamic, so further
# interval changes could be added with very little effort.
#
# All fields except the time are repeated once for each directory provided on
# the command line, so calling with 3 directories will result in 27 fields
# being printed after the time (assuming --no-df is not specified).
#
# Note that the --fortnight and --no-df flags only take effect from that point
# forward in the argument list, so the following example would produce df
# output for the first directory, and weekly intervals for the first two, but
# fortnightly for the last:
#	backup-file-check /tmp/blah1 --no-df /tmp/blah2 --fortnight /tmp/blah3
#

set -e
set -u

RRD=1
DF=1
INTERVAL_1=1
INTERVAL_2=7
INTERVAL_3=31
NOW=`date +%s`
RRD_HEADER=0
DEBUG=0

report_stats()
{
	find "$@" -type f -printf "%T@\t%s\t%p\n" 2>/dev/null | \
	rrd=$RRD findpath="$@" now="$NOW" debug="$DEBUG" \
	interval1="$INTERVAL_1" interval2="$INTERVAL_2" interval3="$INTERVAL_3" \
	perl -we '

sub debugfile ($$$) {
	my ($file, $interval, $time) = @_;
	printf STDERR "%s: newer than %s (%d): %s (%d)\n", $file, scalar localtime($interval),
		$interval, scalar localtime($time), $time if $ENV{"debug"} != 0;
}

	# initialise counters
	my $dayfiles = 0;
	my $weekfiles = 0;
	my $monthfiles = 0;
	my $totalfiles = 0;
	my $totalsize = 0;

	my $now = $ENV{"now"};

	# set cutoff dates
	my $day   = $now - (86400 * $ENV{"interval1"});
	my $week  = $now - (86400 * $ENV{"interval2"});
	my $month = $now - (86400 * $ENV{"interval3"});

	# determine file counts
	while (<>) {
		chomp;
		my ($time, $size, $path) = split(/\s+/, $_, 3);
		if ($time > $day) {
			++$dayfiles;
			debugfile($path, $day, $time);
		}
		if ($time > $week) {
			++$weekfiles;
			debugfile($path, $week, $time);
		}
		if ($time > $month) {
			++$monthfiles;
			debugfile($path, $month, $time);
		}
		++$totalfiles;
		$totalsize += size;
	}

	# print summary
	if ($ENV{"rrd"} != 0) {
		print ":$dayfiles:$weekfiles:$monthfiles:$totalfiles:$totalsize";
	}
	else {
		print "$dayfiles\t$weekfiles\t$monthfiles\t$totalfiles\t$totalsize\t" . $ENV{"findpath"} . "\n";
	}
	'
	if [ "$DF" != "0" ]; then
		df --block-size=1M --portability "$@" | tail -1 | tr -d "%" | \
			awk '{printf ":%s:%s:%s:%s", $2, $3, $4, $5}'
	fi
}

while [ "$#" -gt 0 ]; do
	case "$1" in
	--debug)
		DEBUG=1
		RRD=0
		;;
	--df)
		DF=1
		;;
	--no-df)
		DF=0
		;;
	--fortnight*)
		INTERVAL_2=14
		;;
	--rrd)
		RRD=1
		;;
	--no-rrd)
		RRD=0
		;;
	--week*)
		INTERVAL_2=7
		;;
	--now)
		NOW=$2
		shift
		;;
	-*)
		echo "$PROG: Invalid option ($i) specified - ignored" >&2
		;;
	*)
		# print the RRD header if needed
		if [ "$RRD" -ne 0  -a "$RRD_HEADER" -eq 0 ]; then
			echo -n "$NOW"
			RRD_HEADER=1
		fi
		report_stats "$1"
		;;
	esac
	shift
done

# add a newline if we are in RRD mode
if [ "$RRD" -ne 0 ]; then
	echo ""
fi

