#!/bin/sh

set -e
set -u

PROG="$0"
DAYS=66
PRI=local0.info
DIR=/share/backup/mysql
DATE=`date +%Y%m%d.%H%M`
DBS="`echo "show databases;"|mysql --skip-column-names|grep -ve '^performance_schema$' -e '^information_schema$'`"

message()
{
    test -t 0 && echo "$@"
    logger -t $PROG -p $PRI "$@"
}

mkdir -p $DIR

# Clear out old backups
find $DIR -type f -mtime +$DAYS -print0 | xargs --null --no-run-if-empty /bin/rm

BEGIN=`date +%s`
for i in $DBS; do
    message "Starting dump of $i"
    LAST=`date +%s`
    mysqldump --events --databases $i | gzip --best > $DIR/$i-$DATE.gz
    NOW=`date +%s`
    message "$i dumped in `expr $NOW - $LAST` second(s)."
done
message "MySQL dumps took `expr $NOW - $BEGIN` second(s)."

